### ISSUE TITLE
I cant find the executable

### ISSUE THREAD

**Issue by ell-hanafi** [itshoro/lazer-db-map-converter#2]
when i open the shell and follow the instruction it says:
'LazerDBMapConverter.exe' is not recognized as an internal or external command, operable program or batch file.

please help.

**Comment by itshoro** [comment]
@polyvoru It's a pretty old project, and I was pretty bad at expressing what is necessary.

To run the application you need to compile it yourself currently using VS2017 or up. It requires the sqlite nuget package.

**However in the meantime, I added an already compiled version.**
https://github.com/itshoro/lazer-db-map-converter/releases/tag/1.0

Just download, extract and then follow the instructions of the README on the github page.
Well then it's as easy as `.\LazerDBMapConverter -osz`. :)

Have a nice day! :)
